# Generated by Django 5.1.4 on 2025-11-11 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_requesteddiscipline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discipline",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
