# Generated by Django 5.1.4 on 2025-11-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_discipline_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="discipline",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="RequestedDiscipline",
        ),
    ]
