# Generated by Django 5.1.4 on 2025-11-12 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_discipline_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discipline",
            name="approved_date",
        ),
    ]
