# Generated by Django 5.1.4 on 2025-10-21 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_discipline_admin_delete_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestedDiscipline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discipline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.discipline",
                    ),
                ),
            ],
        ),
    ]
