# Generated by Django 5.1.4 on 2025-11-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_discipline_is_approved_delete_requesteddiscipline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discipline",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
